### 1.Create two numpy arrays. The first array, called arr1 should be of one dimension and consist of six elements of float type. The second array, called arr2 should be of two dimensions and each sub-array should consist of 5 elements of string type. Display these two numpy arrays.

In [1]:
import numpy as np
arr1 = np.array([1.1,2.2,3.3,4.4,5.5,6.6],dtype=float)
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype=str)
print('First Array :')
print(arr1,'\n')
print('Second Array :')
print(arr2)

First Array :
[1.1 2.2 3.3 4.4 5.5 6.6] 

Second Array :
[['1' '2' '3' '4' '5']
 ['6' '7' '8' '9' '10']]


### 2.For the arrays arr1 and arr2 created in Q.No.1, display the following properties: data type and dimensions. Reshape arr1 into a two dimensional array of 2 rows and three columns, and display the reshaped array. Similarly, reshape arr2 into a single dimensional array and display the reshaped array.

In [2]:
print(arr1)
print(arr1.dtype)
print(arr1.shape)

print(arr2)
print(arr2.dtype)
print(arr2.shape)

[1.1 2.2 3.3 4.4 5.5 6.6]
float64
(6,)
[['1' '2' '3' '4' '5']
 ['6' '7' '8' '9' '10']]
<U2
(2, 5)


In [3]:
new_arr1=np.reshape(arr1,(2,3))
print(new_arr1)
new_arr2=np.reshape(arr2,(1,10))
print(new_arr2)

[[1.1 2.2 3.3]
 [4.4 5.5 6.6]]
[['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']]


### 3.Create a two dimensional array called arr3, of 3 rows and 4 columns which is initialized to zeroes. Create another single dimensional array called arr4, with 6 elements and which is initialized to ones. The type of arr4 is int.

In [4]:
arr3 = np.zeros((3,4),dtype=int)
arr4 = np.ones(6,dtype=int)
print(arr3)
print('\n')
print(arr4)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


[1 1 1 1 1 1]


### 4.Create a list called list1 with the elements 10,20,30,40,50. Now, create a numpy array called arr5 from list1, using the method asarray. The data type of arr5 is float. Similarly, create another array called arr6, from list1, using the method fromiter, whose data type is int. Display arr5 and arr6.

In [5]:
list1 = [10,20,30,40,50]
arr5 = np.asarray(list1,dtype=float)
arr6 = np.fromiter(list1,dtype=int)
print('Asarray Method of array :',arr5,'\n')

print('Fromiter method of array :',arr6)

Asarray Method of array : [10. 20. 30. 40. 50.] 

Fromiter method of array : [10 20 30 40 50]


### 5.Create a numpy array called arr7 using the method arange. The starting value of this array is 12 and ending value is 99, with a step size of 3. Use the linspace method to create another array called arr8, where the starting value is 12 and ending value is 99 and which contains 50 evenly spaced elements.

In [6]:
arr7 = np.arange(12,99,3)
arr8 = np.linspace(12,99,50)
print('arange method of array : \n ',arr7,'\n')
print('linspace method of array : \n ',arr8)

arange method of array : 
  [12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81
 84 87 90 93 96] 

linspace method of array : 
  [12.         13.7755102  15.55102041 17.32653061 19.10204082 20.87755102
 22.65306122 24.42857143 26.20408163 27.97959184 29.75510204 31.53061224
 33.30612245 35.08163265 36.85714286 38.63265306 40.40816327 42.18367347
 43.95918367 45.73469388 47.51020408 49.28571429 51.06122449 52.83673469
 54.6122449  56.3877551  58.16326531 59.93877551 61.71428571 63.48979592
 65.26530612 67.04081633 68.81632653 70.59183673 72.36734694 74.14285714
 75.91836735 77.69387755 79.46938776 81.24489796 83.02040816 84.79591837
 86.57142857 88.34693878 90.12244898 91.89795918 93.67346939 95.44897959
 97.2244898  99.        ]


### 6.In the array arr2 defined in Q.No. 1, what is the output of the following statements: print(arr2), print(arr2[0:1]), print(arr2[1][3]), print (arr2[1])
 



In [7]:
print(arr2,'\n'),
print(arr2[0:1],'\n') 
print(arr2[1][3],'\n')
print (arr2[1],'\n')

[['1' '2' '3' '4' '5']
 ['6' '7' '8' '9' '10']] 

[['1' '2' '3' '4' '5']] 

9 

['6' '7' '8' '9' '10'] 



### 7.Create a two dimensional array called arr9 with the following elements: [101, 322, 768], [233, 124, 390], [534, 122, 216]. From arr9, create an array called arr10 which contains the elements 101, 322, 390, 122 using advanced integer indexing. Create another array called arr11 which contains elements of first and second rows, and second and third columns using slicing operations.

In [8]:
arr9 = np.array([[101,322,768],[233,124,390],[534,122,216]],dtype=int)
arr10 = arr9[[0,0,1,2],[0,1,2,1]]
arr11 = arr9[0:2][1:3]
print('array arr9 is :\n',arr9,'\n')

print('Advanced Integer Indexing :',arr10,'\n')

print('Slicing Operation :',arr11,'\n')

array arr9 is :
 [[101 322 768]
 [233 124 390]
 [534 122 216]] 

Advanced Integer Indexing : [101 322 390 122] 

Slicing Operation : [[233 124 390]] 



### 8.From array arr9 created in Q.No. 7, find all elements greater than 200 using boolean indexing, find all non-NaN elements, and find all non-float elements. Find the result of adding arrays arr9 and another array of 3 elements, using the concept of broadcasting.

In [9]:
arr12 = arr9[arr9 > 200]
print('Elements are greater than 200 in arr9 :',arr12,'\n')

arr13 = arr9[~np.isnan(arr9)]
print('Non-NaN Elements in arr9 :',arr13,'\n')

arr14 = arr9[arr9.dtype != 'float']
print('Non-Float Elements in arr9 :',arr14,'\n')

arr15 = np.array([[arr12],[arr13],[arr14]])
arr16 = arr9 + arr15
print('The Broadcasting Method :',arr16)

Elements are greater than 200 in arr9 : [322 768 233 390 534 216] 

Non-NaN Elements in arr9 : [101 322 768 233 124 390 534 122 216] 

Non-Float Elements in arr9 : [[[101 322 768]
  [233 124 390]
  [534 122 216]]] 

The Broadcasting Method : [[array([423, 869, 334, 491, 635, 317])
  array([ 644, 1090,  555,  712,  856,  538])
  array([1090, 1536, 1001, 1158, 1302,  984])]
 [array([ 334,  555, 1001,  466,  357,  623,  767,  355,  449])
  array([225, 446, 892, 357, 248, 514, 658, 246, 340])
  array([ 491,  712, 1158,  623,  514,  780,  924,  512,  606])]
 [array([[[ 635,  856, 1302],
        [ 767,  658,  924],
        [1068,  656,  750]]])
  array([[[223, 444, 890],
        [355, 246, 512],
        [656, 244, 338]]])
  array([[[317, 538, 984],
        [449, 340, 606],
        [750, 338, 432]]])]]


<ipython-input-9-c10511a6a46c>:10: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  arr15 = np.array([[arr12],[arr13],[arr14]])


### 9.For the array arr9, find its transpose. Find the result of joining the arrays arr1 and arr4 along axis 0.
 

In [10]:
arr9_transpose = arr9.T
print('arr9 is\n',arr9,'\n')
print('The transponse of arr9 ',arr9_transpose,'\n')
print('Joining the two arrays arr1 and arr4 along the axis = 0 (Row wise) ')
arr11 = np.array(arr1,dtype=int)
print(np.concatenate((arr11,arr4),axis = 0))

arr9 is
 [[101 322 768]
 [233 124 390]
 [534 122 216]] 

The transponse of arr9  [[101 233 534]
 [322 124 122]
 [768 390 216]] 

Joining the two arrays arr1 and arr4 along the axis = 0 (Row wise) 
[1 2 3 4 5 6 1 1 1 1 1 1]


### 10.Using any two 2-dimensional arrays, demonstrate the working of the methods, hstack, vstack, hsplit and vsplit.






In [11]:
arr2_2 = np.array([[1,2],[3,4]],'\n')
print('hstack:\n',np.hstack(arr2_2),'\n')
print('vstack:\n',np.vstack(arr2_2,),'\n')
print('hsplit:\n',np.hsplit(arr2_2,2),'\n')
print('vsplit:\n',np.vsplit(arr2_2,2),'\n')

hstack:
 [1 2 3 4] 

vstack:
 [[1 2]
 [3 4]] 

hsplit:
 [array([[1],
       [3]], dtype=uint64), array([[2],
       [4]], dtype=uint64)] 

vsplit:
 [array([[1, 2]], dtype=uint64), array([[3, 4]], dtype=uint64)] 

